name: Netlify

on:
  push:
    branches-ignore: 
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      
      - run: yarn install --ci
        
      - uses: nelonoel/branch-name@v1.0.1
      - run: npx json -I -f dist/variables.json -e \"this.playground='https://${env.BRANCH_NAME}shaperone.netlify.app/playground'\"

      - run: yarn build
      
      - name: Publish preview
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: dist
          alias: ${{ env.BRANCH_NAME }}
      
      - name: Status check
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Netlify preview
          conclusion: neutral
          details_url: https://${env.BRANCH_NAME}shaperone.netlify.app
