name: Netlify

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - run: yarn install --ci
      - run: npx json -I -f dist/variables.json -e \"this.playground='$DEPLOY_PRIME_URL/playground'\"
      - run: yarn build
      - uses: nelonoel/branch-name@v1.0.1
      - name: Publish preview
        if: ${{ BRANCH_NAME != 'master' }}
        uses: jsmrcaga/action-netlify-deploy@1.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: dist
          alias: ${{ BRANCH_NAME }}
      - name: Status check
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Netlify preview
          conclusion: neutral
